### ISSUE TITLE
[Feature Request] Google Analytics v4

### ISSUE THREAD

**Issue by WrestlingMob** [foo-dogsquared/hugo-theme-more-contentful#1]
Any chance we can get Google Analytics v4 support?
Thank you.

**Comment by foo-dogsquared** [comment]
I haven't used Google Analytics in a long time but it seems the [related internal template](https://github.com/gohugoio/hugo/blob/534e7155bb504682a37f5663d8c913e439b11e07/tpl/tplimpl/embedded/templates/google_analytics.html) already supports it. You can just [configure to use GA4 through the site config](https://gohugo.io/templates/internal/#configure-google-analytics).

**Comment by foo-dogsquared** [comment]
Nevermind, it seems like the internal template does not exactly support it. Though, [there is an issue that acknowledged this](https://github.com/gohugoio/hugo/issues/9987). I'm closing this issue since I recommend following the upstream issue instead.
